use_frameworks!

platform :ios, '9.0'

target 'JCLogin_Example' do
  pod 'JCLogin', :path => '../'
  pod 'JCZJTest',:path => '../../JCZJTest'

  target 'JCLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
